version: '3.8'
services:
  postgres:
    image: postgres:14
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: hackathon
      POSTGRES_PASSWORD: hackathon
      POSTGRES_DB: hackathon_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:

